// Mocks generated by Mockito 5.4.6 from annotations
// in task_manager/test/widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ui' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:task_manager/models/task.dart' as _i3;
import 'package:task_manager/providers/task_provider.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [TaskProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskProvider extends _i1.Mock implements _i2.TaskProvider {
  MockTaskProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FilterStatus get filter =>
      (super.noSuchMethod(
            Invocation.getter(#filter),
            returnValue: _i2.FilterStatus.all,
          )
          as _i2.FilterStatus);

  @override
  _i2.SortMode get sortMode =>
      (super.noSuchMethod(
            Invocation.getter(#sortMode),
            returnValue: _i2.SortMode.priority,
          )
          as _i2.SortMode);

  @override
  List<_i3.Task> get tasks =>
      (super.noSuchMethod(Invocation.getter(#tasks), returnValue: <_i3.Task>[])
          as List<_i3.Task>);

  @override
  Map<String, int> get statistics =>
      (super.noSuchMethod(
            Invocation.getter(#statistics),
            returnValue: <String, int>{},
          )
          as Map<String, int>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void addTask(_i3.Task? task) => super.noSuchMethod(
    Invocation.method(#addTask, [task]),
    returnValueForMissingStub: null,
  );

  @override
  void deleteTask(String? id) => super.noSuchMethod(
    Invocation.method(#deleteTask, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void toggleComplete(String? id) => super.noSuchMethod(
    Invocation.method(#toggleComplete, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void setFilter(_i2.FilterStatus? filter) => super.noSuchMethod(
    Invocation.method(#setFilter, [filter]),
    returnValueForMissingStub: null,
  );

  @override
  void setSortMode(_i2.SortMode? mode) => super.noSuchMethod(
    Invocation.method(#setSortMode, [mode]),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
