// Mocks generated by Mockito 5.4.6 from annotations
// in task_manager/test/unit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:task_manager/models/task.dart' as _i3;
import 'package:task_manager/services/task_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [TaskService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskService extends _i1.Mock implements _i2.TaskService {
  MockTaskService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.Task> get allTasks =>
      (super.noSuchMethod(
            Invocation.getter(#allTasks),
            returnValue: <_i3.Task>[],
          )
          as List<_i3.Task>);

  @override
  Map<String, int> get statistics =>
      (super.noSuchMethod(
            Invocation.getter(#statistics),
            returnValue: <String, int>{},
          )
          as Map<String, int>);

  @override
  void addTask(_i3.Task? task) => super.noSuchMethod(
    Invocation.method(#addTask, [task]),
    returnValueForMissingStub: null,
  );

  @override
  void deleteTask(String? id) => super.noSuchMethod(
    Invocation.method(#deleteTask, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void toggleComplete(String? id) => super.noSuchMethod(
    Invocation.method(#toggleComplete, [id]),
    returnValueForMissingStub: null,
  );

  @override
  List<_i3.Task> getByStatus({required bool? completed}) =>
      (super.noSuchMethod(
            Invocation.method(#getByStatus, [], {#completed: completed}),
            returnValue: <_i3.Task>[],
          )
          as List<_i3.Task>);

  @override
  List<_i3.Task> sortByPriority() =>
      (super.noSuchMethod(
            Invocation.method(#sortByPriority, []),
            returnValue: <_i3.Task>[],
          )
          as List<_i3.Task>);

  @override
  List<_i3.Task> sortByDueDate() =>
      (super.noSuchMethod(
            Invocation.method(#sortByDueDate, []),
            returnValue: <_i3.Task>[],
          )
          as List<_i3.Task>);
}
